name: personal
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
  jaspr: ^0.22.1
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  rpc_dart_data: ^3.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
