name: career_ledger
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  rpc_dart: ^2.4.0
  rpc_dart_transports: ^1.7.1
  rpc_dart_data: ^3.5.0
  rpc_dart_generator: ^0.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
