name: career_ledger_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  career_ledger:
    path: ../career_ledger
  postgres: ^3.5.9
  uuid: ^4.5.1

  rpc_dart: ^2.4.0
  rpc_dart_transports: ^1.7.1
  rpc_dart_data: ^3.6.0
  rpc_dart_generator: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
